alias iwyu='/google/src/head/depot/google3/devtools/maintenance/include_what_you_use/iwyu.py'
alias fixdepscl='~/bin/fixdepscl.sh'
alias g5='/google/data/ro/projects/shelltoys/g5.sar'
alias dc='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
alias fixdeps='/home/build/devtools/blazeutils/fixdeps_main.par'
alias pa='prodaccess -g'
alias d='cd /usr/local/google/home/amaksimenka/d/google3'
alias rmorig='find . -type f -name '*.orig' -delete'
alias iblaze=/google/data/ro/teams/iblaze/iblaze
alias buildfix='/google/data/ro/teams/ads-integrity/buildfix'
alias bq=/google/bin/releases/bigquery-team/tools/bq.par
alias helix_runner=/google/src/files/head/depot/google3/cloud/helix/tools/helix_runner
alias cclean=/google/src/head/depot/google3/devtools/maintenance/cclean/cclean
